image: golang

pipelines:
  pull-requests:
    '**':
      - step:
          name: Run Tests
          script:
            - |
              export SANDBOX_NAME="bitbucket-pr-${BITBUCKET_PR_ID}"
              export NAMESPACE="hotrod-devmesh"

              # Set up Signadot CLI
              apt update; apt install -y jq
              curl -sSLf https://raw.githubusercontent.com/signadot/cli/installation-script/scripts/install.sh | sh 

              # Create a sandbox
              echo "Creating sandbox ${SANDBOX_NAME}..."
              signadot sandbox apply \
                --set name=${SANDBOX_NAME} \
                --set service=driver \
                --set branch=${BITBUCKET_BRANCH} \
                --set namespace=${NAMESPACE} \
                -f - \
                < ${BITBUCKET_CLONE_DIR}/.signadot/sbx-noop.yaml

              # Run the proxy
              echo "Starting signadot proxy..."
              signadot local proxy --sandbox ${SANDBOX_NAME} \
                --map http://frontend.${NAMESPACE}:8080@localhost:38080 > /tmp/signadot-proxy.log &
              PROXY_PID=$!
              sleep 1
              cat /tmp/signadot-proxy.log

              # Execute the tests
              echo "Executing tests..."
              source bitbucket-pipelines-go.sh
              go install github.com/jstemmer/go-junit-report/v2@latest
              mkdir test-reports
              TEST_FRONTEND_ADDR=localhost:38080 TEST_TARGET_WORKLOAD=driver TEST_SANDBOX_NAME=${SANDBOX_NAME} go test -v \
                ${BITBUCKET_CLONE_DIR}/services/frontend/ | go-junit-report -set-exit-code -out test-reports/integration-report.xml

              # Stop the proxy
              cat /tmp/signadot-proxy.log
              kill ${PROXY_PID}

              echo "Deleting sandbox..."
              signadot sandbox delete ${SANDBOX_NAME}
