apiVersion: signadot.com/v1
kind: SignadotResourcePlugin
metadata:
  name: hotrod-mariadb
spec:
  description: |
    Provision a MariaDB instance for one of HotROD's services.

    Sandbox should provide input 'dbname' for the name of the database.

    Plugin provisioner provides outputs 'host', 'port', 'root_password' for 
    an empty database instance tied to the lifetime of the sandbox.
  type: ExecPod
  execPod:
    imageSpecVersion: v1.0
    template:
      metadata:
        namespace: signadot
      spec:
        serviceAccountName: hotrod-mariadb-plugin
        containers:
        - image: signadot/hotrod-mariadb-plugin:latest
          name: plugin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: signadot
  name: hotrod-mariadb-plugin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: signadot
  name: hotrod-mariadb-plugin
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets", "services"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: signadot
  name: hotrod-mariadb-plugin
subjects:
- kind: ServiceAccount
  namespace: signadot
  name: hotrod-mariadb-plugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hotrod-mariadb-plugin
