apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customer
spec:
  hosts:
  - customer
  http:
  - route:
    - destination:
        host: customer
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: driver
spec:
  hosts:
  - driver
  http:
  # - match:
  #   - headers:
  #       sd-workspace:
  #         exact: feature-fast-rides
  #   route:
  #   - destination:
  #       host: "proxy.signadot.svc.cluster.local"
  #       port:
  #         number: 55939
  - route:
    - destination:
        host: driver
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend
spec:
  hosts:
  - frontend
  http:
  - route:
    - destination:
        host: frontend
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: route
spec:
  hosts:
  - route
  http:
  - route:
    - destination:
        host: route
        subset: v1

---
