name: Go

on:
  push:
    branches: [ main ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: [ main ]


env:
  GO_VERSION: 1.18

jobs:
  # run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      customer: ${{ steps.filter.outputs.customer }}
      driver: ${{ steps.filter.outputs.driver }}
      frontend: ${{ steps.filter.outputs.frontend }}
      route: ${{ steps.filter.outputs.route }}
    steps:
      # The paths-filter action requires a checkout step for push events.
      - if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            customer:
              - 'services/customer/**'
              - 'cmd/customer.go'
              - 'pkg/**'
            driver:
              - 'services/driver/**'
              - 'cmd/driver.go'
              - 'pkg/**'
            frontend:
              - 'services/frontend/**'
              - 'cmd/frontend.go'
              - 'pkg/**'
            route:
              - 'services/route/**'
              - 'cmd/route.go'
              - 'pkg/**'

  build:
    runs-on: ubuntu-latest
    needs: [ changes ]
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - uses: actions/checkout@v2
        with:
          # Goreleaser needs to see git history and tags.
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Go Mod Cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ env.GO_VERSION }}-mod-

      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ env.GO_VERSION }}-build-
      - name: Setup qemu
        uses: docker/setup-qemu-action@v1

      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag
        env:
          GIT_SHA: ${{ github.sha }}
        run: |
          # Make a fake tag so goreleaser will actually push images.
          git tag v0.0.1-snapshot.${GIT_SHA}

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GIT_SHA: ${{ github.sha }}

  run_integration_tests:
    if: ${{ github.event_name == 'pull_request' && needs.changes.outputs.route == 'true' }}
    runs-on: ubuntu-latest
    needs: [ build, changes ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Go Mod Cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ env.GO_VERSION }}-mod-
      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ env.GO_VERSION }}-build-
      - name: Run Integration test on Route service
        env:
          SIGNADOT_API_KEY: ${{ secrets.SIGNADOT_API_KEY }}
          ROUTE_SERVICE_IMAGE: signadot/hotrod:${{ github.sha }}
        run: |
          echo "Image name: $ROUTE_SERVICE_IMAGE"
          cd test/api-test/
          SIGNADOT_API_KEY=${{ secrets.SIGNADOT_API_KEY }} gradle test
      - name: Publish Route Service Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          comment_title: Route Service Test Result
          check_name: Route Service Test Result
          comment_mode: "create new"
          files: test/api-test/build/test-results/**/*.xml
