name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      customer: ${{ steps.filter.outputs.customer }}
      driver: ${{ steps.filter.outputs.driver }}
      frontend: ${{ steps.filter.outputs.frontend }}
      route: ${{ steps.filter.outputs.route }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          customer:
            - 'services/customer/**'
            - 'cmd/customer.go'
            - 'pkg/**'
          driver:
            - 'services/driver/**'
            - 'cmd/driver.go'
            - 'pkg/**'
          frontend:
            - 'services/frontend/**'
            - 'cmd/frontend.go'
            - 'pkg/**'
          route:
            - 'services/route/**'
            - 'cmd/route.go'
            - 'pkg/**'

  build:
    runs-on: ubuntu-latest
    needs: [changes]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: |
        ./build.sh

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker Login
      uses: docker/login-action@v1.9.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build customer image
      if: ${{ needs.changes.outputs.customer == 'true' }}
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: signadot/hotrod-customer:${{ github.sha }}

    - name: Build driver image
      if: ${{ needs.changes.outputs.driver == 'true' }}
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: signadot/hotrod-driver:${{ github.sha }}

    - name: Build frontend image
      if: ${{ needs.changes.outputs.frontend == 'true' }}
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: signadot/hotrod-frontend:${{ github.sha }}
      
    - name: Build route image
      if: ${{ needs.changes.outputs.route == 'true' }}
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: signadot/hotrod-route:${{ github.sha }}

  update_signadot:
    needs: [build, changes]
    runs-on: ubuntu-latest
    steps:
    - name: call signadot API
      id: upsert_workspace
      run: |      
         imageReplacements=()
         if [[ ${{ needs.changes.outputs.customer }} == 'true' ]]
         then
           imageReplacements+=('{"name": "signadot/hotrod-customer", "newTag": "${{ github.sha }}"}')
         fi
         
         if [[ ${{ needs.changes.outputs.driver }} == 'true' ]]
         then
           imageReplacements+=('{"name": "signadot/hotrod-driver", "newTag": "${{ github.sha }}"}')
         fi
         
         if [[ ${{ needs.changes.outputs.frontend }} == 'true' ]]
         then
           imageReplacements+=('{"name": "signadot/hotrod-frontend", "newTag": "${{ github.sha }}"}')
         fi
         
         if [[ ${{ needs.changes.outputs.route }} == 'true' ]]
         then
           imageReplacements+=('{"name": "signadot/hotrod-route", "newTag": "${{ github.sha }}"}')
         fi
         
         printf -v joined '%s,' "${imageReplacements[@]}"
         if [ ${#imageReplacements[@]} -eq 0 ]; then
              echo "no update required"
              exit 1
          else
              echo "${#imageReplacements[@]} image updates found"
          fi
         
         echo ${joined%,}
         RESULT=$(curl -H 'Content-Type: application/json' \
              -H 'Authorization: Bearer ${{ secrets.SIGNADOT_TOKEN }}' \
              -d  "{\"org\": \"signadot\",
                  \"cluster\": \"demo\",
                  \"namespace\": \"hotrod\",
                  \"defaultService\": \"frontend\",
                  \"defaultServicePort\": 8080,
                  \"images\": [ ${joined%,} ] }" \
         https://api.signadot.com/api/v1/repos/signadot/hotrod/pulls/${{ github.event.number }}/workspaces)
         echo $RESULT
         URL=$(jq -r '.previewURLs[0]' <<< $RESULT)
         WORKSPACE=$(jq -r '.workspaceIDs[0]' <<< $RESULT)
         echo "::set-output name=preview::$URL"
         echo "::set-output name=workspace::$WORKSPACE"
      shell: bash
    - name: Update PR with Signadot Preview
      uses: niteoweb/pull_request_status_action@v1.0.0
      with:
        pr_number: ${{ github.event.number }}
        state: success
        repository: signadot/hotrod
        context: "Signadot Workspace Deployed"
        target_url: ${{ steps.upsert_workspace.outputs.preview }}
        description: "Preview URL for your change"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Update PR with Signadot Dashboard URL
      uses: niteoweb/pull_request_status_action@v1.0.0
      with:
        pr_number: ${{ github.event.number }}
        state: success
        repository: signadot/hotrod
        context: "Signadot Dashboard URL"
        target_url: "https://app.signadot.com/workspace/${{ steps.upsert_workspace.outputs.workspace }}"
        description: "Signadot Dashboard"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
